Repository Serferjim/decide-Europa-Autentication, pull requests merged in 2018-12, with the labels that each got.

#4 Unión de ramas masters
  .gitignore
  decide/booth/templates/booth/booth.html
  decide/booth/views.py
  decide/mixnet/funcionamiento_zkp.md
  decide/mixnet/zkp.py
Labels: Medium, enhancement

#15 Merge de Integration a master
  decide/authentication/models.py
  decide/authentication/views.py
Labels: Critical, enhancement

#19 Comprobaciones en backend
  .idea/decide-Europa-Autentication.iml
  .idea/encodings.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/workspace.xml
  README.md
  decide/authentication/tests.py
  decide/authentication/urls.py
  decide/authentication/views.py
  decide/decide/settings.py
Labels: Medium, enhancement

#24 Integration
  .gitignore
  .idea/decide-Europa-Autentication.iml
  .idea/encodings.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  README.md
  decide/authentication/forms.py
  decide/authentication/models.py
  decide/authentication/tests.py
  decide/authentication/urls.py
  decide/authentication/user_register.html
  decide/authentication/views.py
  decide/booth/templates/booth/booth.html
  decide/booth/views.py
  decide/decide/settings.py
  decide/mixnet/funcionamiento_zkp.md
  decide/mixnet/zkp.py
  docker/Dockerfile
Labels: High
